import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { z } from "zod";

const scaffoldInputSchema = z
  .object({
    id: z
      .string()
      .regex(
        /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/,
        "App ID must use lowercase kebab-case."
      ),
    label: z.string().trim().min(2).max(80),
    owner: z.string().trim().min(2).max(80),
    riskTier: z.enum(["standard", "elevated", "critical"]),
    dataClassification: z.enum(["internal", "restricted"])
  })
  .strict();

export type ScaffoldInput = z.infer<typeof scaffoldInputSchema>;

export interface ScaffoldFile {
  path: string;
  content: string;
}

function toPascalCase(value: string): string {
  return value
    .split("-")
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("");
}

export function createAppScaffold(input: ScaffoldInput): ScaffoldFile[] {
  const parsed = scaffoldInputSchema.parse(input);
  const symbol = toPascalCase(parsed.id);
  const permissionPrefix = parsed.id.replaceAll("-", "_");
  const manifest = {
    id: parsed.id,
    name: parsed.label,
    owner: parsed.owner,
    riskTier: parsed.riskTier,
    dataClassification: parsed.dataClassification,
    permissions: [`${permissionPrefix}:read`, `${permissionPrefix}:manage`],
    inheritedControls: [
      "server authorization",
      "strict validation",
      "optimistic concurrency",
      "atomic audit writes"
    ]
  };

  return [
    {
      path: "app.manifest.json",
      content: `${JSON.stringify(manifest, null, 2)}\n`
    },
    {
      path: `server/${parsed.id}-service.ts`,
      content: `export interface ${symbol}Record {
  id: string;
  status: "pending" | "completed";
  version: number;
}

export function list${symbol}Records(
  records: readonly ${symbol}Record[]
): readonly ${symbol}Record[] {
  return records;
}
`
    },
    {
      path: `client/${symbol}Workspace.tsx`,
      content: `export function ${symbol}Workspace() {
  return (
    <section>
      <p>New application</p>
      <h2>${parsed.label}</h2>
      <p>Connect this workspace to explicit domain routes and policies.</p>
    </section>
  );
}
`
    },
    {
      path: `tests/${parsed.id}-service.test.ts`,
      content: `import { describe, expect, it } from "vitest";
import { list${symbol}Records } from "../server/${parsed.id}-service.js";

describe("${parsed.label} service", () => {
  it("returns typed domain records", () => {
    expect(
      list${symbol}Records([
        { id: "${parsed.id}-001", status: "pending", version: 1 }
      ])
    ).toHaveLength(1);
  });
});
`
    },
    {
      path: "README.md",
      content: `# ${parsed.label}

Generated by the Fintech Operations Workbench app accelerator.

## Integration checklist

1. Move the service, workspace, and test into the matching repository folders.
2. Add explicit read/write permissions to the server-owned permission union.
3. Add strict request schemas and explicit routes.
4. Add domain tables, migrations, and synthetic seed data.
5. Register ownership, risk, classification, and permissions in the catalog.
6. Add authorization, stale-version, and audit-rollback coverage.

The generator creates a typed starting point, not a generic workflow engine.
`
    }
  ];
}

export function writeAppScaffold(
  input: ScaffoldInput,
  outputDirectory: string
): ScaffoldFile[] {
  const files = createAppScaffold(input);
  mkdirSync(outputDirectory, { recursive: false });

  for (const file of files) {
    const filePath = join(outputDirectory, file.path);
    mkdirSync(dirname(filePath), { recursive: true });
    writeFileSync(filePath, file.content, { encoding: "utf8", flag: "wx" });
  }

  return files;
}
